### ISSUE TITLE
This plugin generated a warning from the characteristic 'Current Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined).

### ISSUE THREAD

**Issue by blassox** [cicciovo/homebridge-samsung-airconditioner#26]
Hi, I'm using your plugin from the very beginning, finding it a smart alternative to smartthings.
I've seen today you're on the project again and I'm very happy since latest homebridge implementation has cut it out from working.
I've tested it right now and it runs pretty well (just annoying messages 'this plugin slows down homebridge..') 
But I left you a warning from my HB 1.3.9 stable: 'This plugin generated a warning from the characteristic 'Current Heater-Cooler State': characteristic value expected valid finite number and received "undefined" (undefined).' 
I've checked with "userAllowedMode": "cool" and without

I've two samsung AR5500M 

Let me know if I can help

Giovanni

**Comment by cicciovo** [comment]
Hi Giovanni. I Will rewrite this plugin because in the old version i had the warning this plugin slow down homebridge. Now i haven’t this warning. But in 2 case i see the warning. I think that in some case the connection is not fast so i restart the internet router and it’s ok. The undefined appear because homekit don’t see the value in a early time. If you copy and paste the command that see in  homebridge in your terminal shell you see that the result is ok. Try to restart your router and your hub (Appletv or other)

**Comment by cicciovo** [comment]
Solved with new version!
